apiVersion: v1
kind: Service
metadata:
  name: {{ include "testsb.fullname" . }}
  labels:
    {{- include "testsb.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace.business }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "testsb.selectorLabels" . | nindent 4 }}
